package org.wesc.ssm.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.wesc.ssm.dao.entity.UcUser;
import org.wesc.ssm.dao.entity.UcUserExample;

public interface UcUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    long countByExample(UcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    int deleteByExample(UcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    int insert(UcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    int insertSelective(UcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    List<UcUser> selectByExampleWithRowbounds(UcUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    List<UcUser> selectByExample(UcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    UcUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UcUser record, @Param("example") UcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UcUser record, @Param("example") UcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UcUser record);
}